sudo: required
services:
  - docker

before_install:
  - docker build -t jakubbboza/docker-react:latest -f Dockerfile.dev .

script:
  - docker run jakubbboza/docker-react:latest npm run test -- --coverage